import os
import asyncio
import time
import feedparser
import random
import re
import edge_tts
from groq import Groq
from datetime import datetime, timezone
from PIL import Image, ImageDraw, ImageFont
import textwrap

# إعدادات
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
client = Groq(api_key=GROQ_API_KEY)

def create_enhanced_thumbnail(title_text):
    try:
        # 1. فتح الصورة الأصلية (الرجل بداخل غرفة العمليات المالية)
        img = Image.open("podcast_cover.jpg")
        width, height = img.size
        draw = ImageDraw.Draw(img)

        # 2. إعداد الخط - نستخدم خطاً عريضاً ليكون العنوان هجومياً وجاذباً
        try:
            # مسار الخط الافتراضي في بيئة GitHub Actions (Ubuntu)
            font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf", 75)
        except:
            font = ImageFont.load_default()

        # 3. معالجة النص: تقصير العنوان إذا كان طويلاً جداً وتنظيمه في أسطر
        # العناوين القصيرة (حتى 20 حرفاً للسطر) تزيد من نسبة النقر لأنها تُقرأ بسرعة
        lines = textwrap.wrap(title_text, width=20)
        
        # 4. تحديد موقع البداية (في الجزء العلوي لترك وجه الشخص واضحاً)
        y_text = 80 
        
        for line in lines:
            # حساب إحداثيات التوسيط
            left, top, right, bottom = draw.textbbox((0, 0), line, font=font)
            line_width = right - left
            x_text = (width - line_width) / 2
            
            # 5. إضافة تأثير البروز (تكرار النص كظل خلفي عميق)
            # رسم النص باللون الأبيض مع إطار أسود سميك جداً (Stroke) لضمان الوضوح فوق أي خلفية
            draw.text((x_text, y_text), line, font=font, fill="white", 
                      stroke_width=5, stroke_fill="black")
            
            y_text += 95 # المسافة بين الأسطر

        # 6. حفظ الصورة النهائية بنفس الاسم ليتم رفعها تلقائياً
        img.save("podcast_cover.jpg")
        print("Success: High-CTR Thumbnail generated!")
    except Exception as e:
        print(f"Error during thumbnail creation: {e}")

async def main():
    # 1. جلب المقالات من RSS
    rss_url = "https://www.economist.com/latest/rss.xml"
    feed = feedparser.parse(rss_url)
    if not feed.entries: return

    entry = random.choice(feed.entries)
    title = entry.title
    summary = re.sub('<[^<]+?>', '', entry.summary)

    # 2. توليد سكريبت البودكاست عبر Groq
    script_prompt = f"Write a detailed professional podcast script in English about: {title}. Based on this context: {summary}. Make it around 300-400 words long."
    chat_response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": script_prompt}]
    )
    podcast_script = chat_response.choices[0].message.content

    # 3. توليد الوصف لليوتيوب
    desc_prompt = f"Create a short SEO description for a podcast titled: {title}"
    desc_response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": desc_prompt}]
    )
    description = desc_response.choices[0].message.content

    # --- هنا تمت إضافة دالة تعديل الصورة ---
    create_enhanced_thumbnail(title)
    # ---------------------------------------

    # 4. تحويل السكريبت إلى صوت
    audio_file = "episode.mp3"
    communicate = edge_tts.Communicate(podcast_script, "en-US-ChristopherNeural")
    await communicate.save(audio_file)
    
    # 5. إنشاء ملف RSS
    run_num = os.getenv("GITHUB_RUN_NUMBER", "1")
    timestamp = int(time.time())
    audio_url = f"https://github.com/eslamtechautomation-ctrl/TrustMask-Bot-main/releases/download/v{run_num}/episode.mp3"
    
    rss_template = f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" 
    xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" 
    xmlns:content="http://purl.org/rss/1.0/modules/content/"
    xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <atom:link href="https://eslamtechautomation-ctrl.github.io/TrustMask-Bot-main/podcast.xml" rel="self" type="application/rss+xml" />
    <title>The Economic Edge: Master Your Wealth</title>
    <link>https://familytvr.blogspot.com/</link>
    <language>en-us</language>
    <itunes:author>Family TVR</itunes:author>
    <itunes:summary>Insightful analysis of global economics.</itunes:summary>
    <itunes:owner>
        <itunes:name>Eslam Tech</itunes:name>
        <itunes:email>eslammosde@gmail.com</itunes:email>
    </itunes:owner>
    <itunes:image href="https://raw.githubusercontent.com/eslamtechautomation-ctrl/TrustMask-Bot-main/refs/heads/main/podcast_cover.jpg" />
    <description><![CDATA[Daily economic insights generated by AI.]]></description>
    <item>
        <title>{title}</title>
        <description>{description}</description>
        <pubDate>{datetime.now(timezone.utc).strftime("%a, %d %b %Y %H:%M:%S +0000")}</pubDate>
        <enclosure url="{audio_url}" length="1048576" type="audio/mpeg"/>
        <guid>v{run_num}_{timestamp}</guid>
    </item>
</channel>
</rss>"""
    
    with open("podcast.xml", "w", encoding="utf-8") as f:
        f.write(rss_template)

if __name__ == "__main__":
    asyncio.run(main())
