name: Podcast Automation
on:
  schedule:
    - cron: '0 */3 * * *' # تحديث كل 3 ساعات
  workflow_dispatch:

jobs:
  automate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install
        run: pip install feedparser groq edge-tts 

      - name: Install dependencies
        run: | 
         pip install feedparser groq edge-tts newspaper3k

        
      - name: Run
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: python main.py
      - name: Update Files
        run: |
          git config --global user.name "Action"
          git config --global user.email "action@github.com"
          git add .  # أضف كل شيء تم إنشاؤه (بما في ذلك podcast.xml الجديد)
          git commit -m "Auto Update RSS" || echo "No changes"
          git push origin main
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          files: episode.mp3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
